contas/urls.py
from django.urls import path
from contas.views import registrar

app_name = "contas"
urlpatterns = [
    path('registrar/', registrar, name='registrar')
]

cursos/urls.py
from django.urls import path

from cursos.views import cursos, curso

app_name = "cursos"
urlpatterns = [
    path('', cursos, name="lista"),
    path('<str:sigla>/', curso, name="curso")

]

lms/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path("cursos/", include("cursos.urls")),
    path("contas/", include("contas.urls")),
]

contas/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager


class Usuario(AbstractBaseUser):
    email = models.EmailField(unique=True)
    nome = models.CharField(max_length=120)

    # quem será o tipo de campo de usuário
    USERNAME_FIELD = "email"
    # campos obrigatórios
    REQUIRED_FIELDS = ["nome"]

    # o AbstractBaseUser não tem objects, então devemos criar um
    # UserManager interface de usuário com o DB para salvar, alterar, entre outras coisas
    objects = UserManager()

    # precisamos informar ao Django qual AUTH_USER_MODEL, em settings.py
    # AUTH_USER_MODEL = "contas.Usuario"

core/models.py
from django.db import models

# Create your models here.

cursos/models.py
from django.db import models


class Curso(models.Model):
    nome = models.CharField(max_length=120)
    sigla = models.CharField(max_length=15)
    descricao = models.TextField()

contas/views.py
from django.shortcuts import render, redirect
from contas.models import Usuario
from django.contrib.auth import login, authenticate

def registrar(request):
    if request.POST:
        email = request.POST.get("email")
        nome = request.POST.get("nome")
        senha = request.POST.get("password")
        senha2 = request.POST.get("password2")

        if senha == senha2:
            usuario = Usuario()
            usuario.email = email
            usuario.nome = nome
            # método do AbstractBaseUser para criptografar a senha
            usuario.set_password(senha)
            usuario.save()
            authenticate(username=usuario.email, password=senha)
            login(request, usuario)
            return redirect("home")
    else:
        return render(request, 'registrar.html')

core/views.py
from django.shortcuts import render


def index(request):
    context = {
        "titulo": "Faculdade Impacta"
    }
    return render(request, "index.html", context)

cursos/views.py
from django.shortcuts import render

from cursos.models import Curso


def cursos(request):
    context = {
        "titulo": "Lista de Cursos",
        "cursos": Curso.objects.all()
    }
    return render(request, "cursos.html", context)


def curso(request, sigla):
    curso = Curso.objects.get(sigla=sigla)
    context = {
        "curso": curso
    }
    return render(request, 'curso.html', context)

contas/templates/entrar.html
{% extends "base.html" %}

{% block conteudo %}


<h1>Entrar</h1>

<form
	method="POST"
	action=""
>
{% csrf_token %}
	<p>
		<label for="campo-email" >E-mail:</label>
		<input type="email" name="email" id="campo-email" required />
	</p>
	<p>
		<label for="campo-senha">Senha:</label>
		<input type="password" name="password" id="campo-senha" required />
	</p>
	<p>
		<label>
			Lembrar de Mim? <input type="checkbox" name	"lembrar" value="SIM" />
		</label>
		<a href="esqueci.html">Esqueceu a senha?</a>
	</p>
	<p>
		<input type="submit" value="Entrar" />
	</p>
</form>
{% endblock %}

contas/templates/registrar.html
{% extends "base.html" %}
{% load static %}

{% block conteudo %}
<h1>Cadastrar</h1>

<form method="POST" action="">
    {% csrf_token %}
    <p>
        <label for="campo-email">E-mail:</label>
        <input type="email" name="email" id="campo-email" required />
    </p>
    <p>
        <label for="campo-nome">Nome Completo:</label>
        <input type="text" name="nome" id="campo-nome" required />
    </p>
    <p>
        <label for="campo-nascimento" >Data de Nascimento:</label>
        <input type="date" name="nascimento" id="campo-nascimento" required />
    </p>
    <p>
        <label for="campo-password">Senha:</label>
        <input type="password" name="password" id="campo-password" required />
    </p>
    <p>
        <label for="campo-password2">Confirme sua Senha:</label>
        <input type="password" name="password2" id="campo-password2" required />
    </p>
    <p>
        <input type="submit" value="Entrar" />
    </p>
</form>
{% endblock %}

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" />
	<title>Faculdade Impacta de Tecnologia</title>
	<link rel="icon" href="{% static 'favicon.ico' %}" />
	<meta name="viewport" content="initial-scale=1">
	<link rel="stylesheet" href="{% static 'css/site.css' %}" />
    <script src="{% static 'scripts/script.js' %}"></script>
    {% block scripts %}    
    {% endblock  %}
</head>
<body>
	<header>
		<a href="{% url 'home' %}">
			<img src="{% static 'imagens/logo.png' %}" width="250px" />
		</a>
		<div class="titulo">
			<h1>Faculdade Impacta de Tecnologia</h1>
			<h2>A TECNOLOGIA MUDA O SEU FUTURO</h2>
		</div>
		<nav>
			<h3>Navegue pelo nosso site</h3>
			<ul>
				<li><a href="{% url 'cursos:lista' %}" >Cursos</a></li>
				<li><a href="premios.html" >Prêmios</a></li>
				<li><a href="eventos.html" >Eventos</a></li>
				{% if user.is_authenticated %}
					<li>Olá {{ user }}</li>
					<li><a href="entrar.html" >Sair</a></li>
				{% else %}
					<li><a href="entrar.html" >Entrar</a></li>
					<li><a href="{% url 'contas:registrar' %}" >Registrar</a></li>
				{% endif %}
			</ul>
		</nav>
	</header>
	<main>
		{% block conteudo %}
        {% endblock %}
	</main>
	<footer>
		<strong>11 3254-8300 - Impacta 2018 - Todos os direitos reservados.</strong>
	</footer>
</body>
</html>

core/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" />
	<title>Faculdade Impacta de Tecnologia</title>
	<link rel="icon" href="favicon.ico" />
	<meta name="viewport" content="initial-scale=1">
	<link rel="stylesheet" href="css/site.css" />
	<script src="scripts/script.js"></script>
</head>
<body>
	<header>
		<a href="index.html">
			<img src="imagens/logo.png" width="250px" />
		</a>
		<div class="titulo">
			<h1>Faculdade Impacta de Tecnologia</h1>
			<h2>A TECNOLOGIA MUDA O SEU FUTURO</h2>
		</div>
		<nav>
			<h3>Navegue pelo nosso site</h3>
			<ul>
				<li><a href="{% url 'cursos:lista' %}" >Cursos</a></li>
				<li><a href="premios.html" >Prêmios</a></li>
				<li><a href="eventos.html" >Eventos</a></li>
				<li><a href="entrar.html" >Entrar</a></li>
			</ul>
		</nav>
	</header>
	<main>
		<h1>{{ titulo }}</h1>
		<section>
			<h2>Conheça nossos Cursos</h2>
			<p>
				Considerada uma das melhores faculdades com foco em tecnologia do País, a <strong>Faculdade Impacta</strong> oferece cursos de <em>Graduação</em>, <em>Pós-Graduação</em> e <em>MBA</em> e cursos técnicos.<br/>
				Conheça quais são as áreas de conhecimento que a Impacta aborda e saiba um pouco mais sobre cada curso:
			</p>
			
			<figure>
				<img src="imagens/graduacao.jpg" />
				<img src="imagens/tecnico.jpg" />
				<img src="imagens/up.jpg" />
				<img src="imagens/mba.jpg" />
			</figure>
		</section>
	</main>
	<footer>
		<strong>11 3254-8300 - Impacta 2018 - Todos os direitos reservados.</strong>
	</footer>
</body>
</html>

cursos/templates/curso.html
{% extends "base.html" %} 
{% load static %} 
{% block scripts %}
<link rel="stylesheet" href="{% static 'css/cursos.css' %}" /> 
{% endblock %} 

{% block conteudo %}
<h1>{{ curso.nome }}</h1>
<section class="sobre">
	<h2>Sobre o Curso</h2>
	<p>
		{{ curso.descricao }}
	</p>
</section>
<section class="informacoes">
	<h2>Informações Adicionais</h2>

	<h3>Período</h3>
	<ul>
		{% for per in curso.periodo %}
			<li>{{ per }}</li>
		{% endfor %}
	</ul>

	<h3>Duração</h3>
	<p>{{ curso.duracao }}</p>

	<a href="disciplinas">Grade Curricular</a>
</section>
{% endblock %}

cursos/templates/cursos.html
{% extends 'base.html' %}

{% block conteudo %}
<h1>{{ titulo }}</h1>
{% for curso in cursos %}
<article class="curso">
    <h2 class="titulo">
        <a href="{{ curso.sigla }}">
            {{ curso.nome }}
        </a>
    </h2>
    <p class="descricao">
        {{ curso.descricao }}
    </p>
</article>
{% endfor %}
{% endblock %}